---
deployment:
  tasks:
    # Set up deployment paths
    - export DEPLOYPATH=/home/myfrovov/public_html/
    - export FASTIFYPATH=/home/myfrovov/fastify-backend/
    - export ROOTPATH=/home/myfrovov/
    
    # Deploy Express frontend files
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R middleware $DEPLOYPATH
    - /bin/cp -R models $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp proxy-server.js $DEPLOYPATH
    
    # Deploy template .env files (if they don't exist)
    - if [ ! -f $DEPLOYPATH.env ]; then /bin/cp deployment/.env.express.example $DEPLOYPATH.env; fi
    
    # Deploy Fastify backend
    - /bin/mkdir -p $FASTIFYPATH
    - /bin/cp -R fastify-backend/* $FASTIFYPATH
    - if [ ! -f $FASTIFYPATH.env ]; then /bin/cp deployment/.env.fastify.example $FASTIFYPATH.env; fi
    
    # Deploy PM2 ecosystem config
    - /bin/cp deployment/ecosystem.config.js $ROOTPATH
    
    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod 755 $FASTIFYPATH
    - /bin/chmod 600 $DEPLOYPATH.env
    - /bin/chmod 600 $FASTIFYPATH.env
    
    # Restart services (only if they exist)
    - source $ROOTPATH/nodevenv/freshshare1.3/14/bin/activate && pm2 reload all || echo "PM2 not available or no processes to reload"
