name: Deploy to cPanel

on:
  push:
    branches: [ restore_branch ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create Express .env file
      run: |
        echo "# MongoDB Atlas Connection" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=FreshShareDB" >> .env
        echo "PORT=3001" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FASTIFY_BACKEND_URL=http://localhost:8080" >> .env
        echo "NODE_ENV=production" >> .env

    - name: Create Fastify .env file
      run: |
        mkdir -p fastify-backend
        echo "PORT=8080" > fastify-backend/.env
        echo "DATABASE_URL=postgres://myfrovov_freshshare_user:BjgjX2Vev2vmLwh@localhost:5432/myfrovov_freshshare" >> fastify-backend/.env
        echo "NODE_ENV=production" >> fastify-backend/.env

    - name: Make startup scripts executable
      run: |
        chmod +x start-express.sh
        chmod +x fastify-backend/start-fastify.sh
        
    - name: Verify scripts exist
      run: |
        if [ ! -f "start-express.sh" ]; then
          echo "ERROR: start-express.sh is missing!"
          exit 1
        fi
        if [ ! -f "fastify-backend/start-fastify.sh" ]; then
          echo "ERROR: fastify-backend/start-fastify.sh is missing!"
          exit 1
        fi
        echo "Scripts verified successfully"

    - name: SFTP Deploy to cPanel
      uses: wlixcc/SFTP-Deploy-Action@v1.2.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.SFTP_PORT }}
        username: myfrovov
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}
        sftp_only: true
        local_path: ./*
        remote_path: public_html/
        rsyncArgs: --exclude=node_modules --exclude=.git --exclude=.github --exclude=deployment-packages --exclude=deployment --exclude=data/**

    - name: Post-deployment restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: myfrovov
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SFTP_PORT }}
        script: |
          # Make scripts executable
          chmod +x ~/public_html/start-express.sh
          chmod +x ~/public_html/fastify-backend/start-fastify.sh
          
          # Start Fastify backend first
          cd ~/public_html/fastify-backend
          npm install --production
          pkill -f "node.*server.ts" || true
          nohup ./start-fastify.sh > fastify.log 2>&1 &
          
          # Wait for Fastify to initialize
          sleep 5
          
          # Start Express server
          cd ~/public_html
          npm install --production
          pkill -f "node server.js" || true
          nohup ./start-express.sh > express.log 2>&1 &
          
          # Verify services are running
          sleep 3
          ps aux | grep node
