name: Deploy to cPanel

on:
  push:
    branches: [ restore_branch ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create Express .env file
      run: |
        echo "# MongoDB Atlas Connection" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=FreshShareDB" >> .env
        echo "PORT=3001" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FASTIFY_BACKEND_URL=http://localhost:8080" >> .env
        echo "NODE_ENV=production" >> .env

    - name: Create Fastify .env file
      run: |
        mkdir -p fastify-backend
        echo "PORT=8080" > fastify-backend/.env
        echo "DATABASE_URL=postgres://myfrovov_freshshare_user:BjgjX2Vev2vmLwh@localhost:5432/myfrovov_freshshare" >> fastify-backend/.env
        echo "NODE_ENV=production" >> fastify-backend/.env

    - name: Verify scripts exist
      run: |
        if [ ! -f "start-express.sh" ]; then
          echo "ERROR: start-express.sh is missing!"
          exit 1
        fi
        if [ ! -f "fastify-backend/start-fastify.sh" ]; then
          echo "ERROR: fastify-backend/start-fastify.sh is missing!"
          exit 1
        fi
        echo "Scripts verified successfully"

    - name: Debug list startup scripts
      run: |
        ls -la
        ls -la fastify-backend || true

    - name: Make startup scripts executable
      run: |
        chmod +x start-express.sh
        chmod +x fastify-backend/start-fastify.sh
        
    - name: Set up SSH key
      run: |
        # Create SSH directory with proper permissions
        mkdir -p ~/.ssh || true
        chmod 700 ~/.ssh
        
        # Write the private key with proper formatting
        echo "${{ secrets.actions_deploy_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add server to known hosts
        ssh-keyscan -p ${{ secrets.SFTP_PORT }} -H ${{ secrets.FTP_SERVER }} >> ~/.ssh/known_hosts 2>/dev/null || true
        
        # Debug: Check key format
        echo "Key starts with:"
        head -1 ~/.ssh/id_rsa
        echo "Key ends with:"
        tail -1 ~/.ssh/id_rsa
        
        # Test SSH connection
        ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }} myfrovov@${{ secrets.FTP_SERVER }} echo "SSH connection successful"

    - name: Ensure remote directories exist
      run: |
        ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }} myfrovov@${{ secrets.FTP_SERVER }} 'mkdir -p ~/public_html ~/public_html/fastify-backend'

    - name: SFTP Deploy to cPanel
      uses: wlixcc/SFTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        port: ${{ secrets.SFTP_PORT }}
        username: myfrovov
        ssh_private_key: ${{ secrets.actions_deploy_key }}
        ssh_passphrase: ""
        sftp_only: true
        local_path: ./*
        remote_path: public_html/
        rsyncArgs: --exclude=node_modules --exclude=.git --exclude=.github --exclude=deployment-packages --exclude=deployment --exclude=data/**

    - name: Post-deployment restart services
      run: |
        ssh -o BatchMode=yes -o ConnectTimeout=10 -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }} myfrovov@${{ secrets.FTP_SERVER }} '
          # Detect Node.js paths on cPanel
          echo "Detecting Node.js installation..."
          
          # Common cPanel Node.js paths to check
          NODE_PATHS=(
            "/opt/cpanel/ea-nodejs18/bin"
            "/opt/cpanel/ea-nodejs20/bin"
            "/usr/local/bin"
            "/usr/bin"
            "$HOME/nodevenv/public_html/18/bin"
            "$HOME/.nvm/versions/node/v18.*/bin"
          )
          
          NODE_BIN=""
          NPM_BIN=""
          
          for path in "${NODE_PATHS[@]}"; do
            if [ -f "$path/node" ] && [ -f "$path/npm" ]; then
              NODE_BIN="$path/node"
              NPM_BIN="$path/npm"
              echo "Found Node.js at: $NODE_BIN"
              break
            fi
          done
          
          # Fallback to system PATH
          if [ -z "$NODE_BIN" ]; then
            NODE_BIN=$(which node 2>/dev/null || echo "node")
            NPM_BIN=$(which npm 2>/dev/null || echo "npm")
            echo "Using system PATH: $NODE_BIN"
          fi
          
          # Make scripts executable
          chmod +x ~/public_html/start-express.sh
          chmod +x ~/public_html/fastify-backend/start-fastify.sh
          
          # Start Fastify backend first
          cd ~/public_html/fastify-backend
          echo "Installing Fastify dependencies..."
          $NPM_BIN install --production || echo "npm install failed, continuing..."
          pkill -f "node.*server.ts" || true
          nohup ./start-fastify.sh > fastify.log 2>&1 &
          
          # Wait for Fastify to initialize
          sleep 5
          
          # Start Express server
          cd ~/public_html
          echo "Installing Express dependencies..."
          $NPM_BIN install --production || echo "npm install failed, continuing..."
          pkill -f "node server.js" || true
          nohup ./start-express.sh > express.log 2>&1 &
          
          # Verify services are running
          sleep 3
          ps aux | grep node || echo "No node processes found"
        '
