name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create Express .env file
      run: |
        echo "MONGODB_HOST=${{ secrets.MONGODB_HOST }}" > .env
        echo "MONGODB_DB=FreshSareDB" >> .env
        echo "PORT=3001" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FASTIFY_BACKEND_URL=http://localhost:8080" >> .env

    - name: Create Fastify .env file
      run: |
        mkdir -p fastify-backend
        echo "PORT=8080" > fastify-backend/.env
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> fastify-backend/.env
        echo "NODE_ENV=production" >> fastify-backend/.env

    - name: FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 162.0.235.133
        username: myfrovov
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        exclude: |
          **/node_modules/**
          **/.git/**
          **/.github/**
