name: Deploy to cPanel

on:
  push:
    branches: [ restore_branch ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Create Express .env file
      run: |
        echo "# MongoDB Atlas Connection" > .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=FreshShareDB" >> .env
        echo "PORT=3001" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "FASTIFY_BACKEND_URL=http://localhost:8080" >> .env
        echo "NODE_ENV=production" >> .env

    - name: Create Fastify .env file
      run: |
        mkdir -p fastify-backend
        echo "PORT=8080" > fastify-backend/.env
        echo "DATABASE_URL=postgres://myfrovov_freshshare_user:BjgjX2Vev2vmLwh@localhost:5432/myfrovov_freshshare" >> fastify-backend/.env
        echo "NODE_ENV=production" >> fastify-backend/.env

    - name: Make startup scripts executable
      run: |
        chmod +x start-express.sh
        chmod +x fastify-backend/start-fastify.sh

    - name: FTP Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/
        exclude: |
          **/node_modules/**
          **/.git/**
          **/.github/**
          **/deployment-packages/**
          **/deployment/**

    - name: Post-deployment restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          cd ~/public_html/fastify-backend
          npm install --production
          nohup ./start-fastify.sh > fastify.log 2>&1 &
          cd ~/public_html
          npm install --production
          nohup ./start-express.sh > express.log 2>&1 &
